name: $(Date:yyyyMMdd)$(Rev:rr)

trigger:
- master

variables:
- group: powershell-gallery

stages:
- stage: test
  displayName: Test
  jobs:
  - job: unit_test
    displayName: Unit testing
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: .\test.ps1
      workingDirectory: $(build.sourcesDirectory)
      displayName: Running unit tests

    - task: PublishTestResults@2
      displayName: Public tests results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: output.xml
        failTaskOnFailedTests: true
      
- stage: deploy
  displayName: Deployment
  jobs:
  - job: psgallery
    displayName: Publishing to PSGallery
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: .\publish.ps1
      env: {
        NUGET_API_KEY: $(nuget-api-key)
      }